// src/components/Clock.vue
<template>
    <div class="clock">
        <span>{{ time }}</span>
    </div>
</template>

<script>
  const options = {
    weekday: 'short',
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  }
  export default {
    name: 'clock',
    data () {
      return {
        time: (new Date()).toLocaleTimeString('en-gb', options).replace(/,/g, ' ')
      }
    },
    methods: {
      updateTime () {
        let now = new Date()
        this.time = now.toLocaleTimeString('en-gb', options).replace(/,/g, ' ')
      }
    },
    mounted () {
      setInterval(this.updateTime, 1000)
    }
  }
</script>

<style>
</style>

// src/components/shared/Clock.jsx
import React from 'react';

const options = {
  weekday: 'short', year: 'numeric', month: 'short',
  day: 'numeric', hour: '2-digit', minute: '2-digit'
};

function FormattedDate(props) {
  return <div>{props.date.toLocaleTimeString('en-gb', options).replace(/,/g, ' ')}</div>;
}

class Clock extends React.Component {
  constructor(props) {
    super(props);
    this.state = { date: new Date() };
  }

  componentDidMount() {
    this.timerID = setInterval(
      () => this.tick(),
      1000
    );
  }

  componentWillUnmount() {
    clearInterval(this.timerID);
  }

  tick() {
    this.setState({
      date: new Date()
    });
  }

  render() {
    return (
      <FormattedDate date={this.state.date} />
    );
  }
}

Clock.propTypes = {
  date: React.PropTypes.object
};

export default Clock;
